# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/demo_testcase_user_pwd_login.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseDemoTestcaseUserPwdLogin(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "mobile-pwd-password-login_type-agency_channel_code": "${P(testdata/userpwdlogindata.csv)}"
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("zhb_user_pwd_login").base_url("https://pc.zuihuibao.cn").verify(False)
    )

    teststeps = [
        Step(
            RunRequest("user_pwd_login_successs")
            .post("/yiiapp/user-pwd/user-pwd-login")
            .with_params(
                **{
                    "mobile": "$mobile",
                    "pwd": "$pwd",
                    "password": "$password",
                    "login_type": "$login_type",
                    "agency_channel_code": "$agency_channel_code",
                }
            )
            .with_headers(**{"Content-Type": "application/x-www-form-urlencoded"})
            .extract()
            .with_jmespath('headers."Set-Cookie"', "zhbsession")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("my info")
            .post("/yiio2o/user/my-info")
            .with_headers(
                **{
                    "Content-Type": "application/x-www-form-urlencoded",
                    "Cookie": "$zhbsession",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("price-configuration-merge")
            .post("/yiiapp/car-ins/price-configuration-merge")
            .with_headers(
                **{
                    "Content-Type": "application/x-www-form-urlencoded",
                    "Cookie": "$zhbsession",
                }
            )
            .with_data({"province": "云南", "city": "昭通", "product_source": "web"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.data.selected_province", "云南")
            .assert_equal("body.data.ins_companies[0].insurance_company", "TAIPINGYANG")
            .assert_equal("body.data.ins_companies[0].district", "太保邵通01")
            .assert_equal("body.data.ins_companies[0].com_id", "1115141001")
        ),
    ]


if __name__ == "__main__":
    TestCaseDemoTestcaseUserPwdLogin().test_start()
